version: '3'
services:
  app:
    build: .
    restart: always
    network_mode: host
    depends_on:
      - "rabbit"

  rabbit:
    image: rabbitmq:management
    expose:
      - 15672
      - 5672
    network_mode: host
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1